spring.application.name=healthapi

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/healthdb
spring.datasource.username=healthuser
spring.datasource.password=healthuser

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

logging.level.hibernate.SQL=info
logging.level.org.springframework.security.web=trace

spring.servlet.multipart.max-request-size=30MB
spring.servlet.multipart.max-file-size=10MB

com.healthapi.upload.path=upload

anthropic.api.key=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